Ecommerce selenium scraping
mate-academy/py-ecommerce-selenium-scraping pull request #99
Opened 2023-08-13 14:50 UTC by gleblitvinenko

2023-08-13 16:39 UTC, vsmutok requested changes

2023-08-13 16:39 UTC, vsmutok commented on app/parse.py
> +        )
All code looks Good, but what happens if some product doesn't have description or rating?

2023-08-13 16:39 UTC, vsmutok commented on app/parse.py
> +)
better to create class Logger

2023-08-13 16:39 UTC, vsmutok commented on app/parse.py
> +)
Also a good practice to use logging more frequently

2023-08-14 08:29 UTC, ArsenPidhoretskyi requested changes

2023-08-14 08:29 UTC, ArsenPidhoretskyi commented on app/parse.py
> +            LoggerFactory._LOG.setLevel(logging.DEBUG)
Create mapping for this instead of duplicate if-else

2023-08-14 13:09 UTC, vasylhnatiuk approved these changes

2023-08-14 13:10 UTC, vasylhnatiuk approved these changes

2026-03-10 17:46 UTC, closed without merging